name: CI

on: push

jobs:
  test-e2e:
    uses: jill64/playwright-config/.github/workflows/duplex-playwright.yml@164f3196faa6d87424822469d554d5a1ad7464ac # v2.4.1
    with:
      hosting-provider: vercel
