name: CI

on: push

jobs:
  test-e2e:
    uses: jill64/playwright-config/.github/workflows/duplex-playwright.yml@d09c4898d1681a64b001e86e2327f1aa7a772422 # v2.3.1
    with:
      hosting-provider: vercel
