name: CI

on: push

jobs:
  test-e2e:
    uses: jill64/playwright-config/.github/workflows/duplex-playwright.yml@374b1a370d028014cc9f0a1209921007ceb69018 # v2.2.2
    with:
      hosting-provider: vercel
