name: CI

on: push

jobs:
  test-e2e:
    uses: jill64/playwright-config/.github/workflows/duplex-playwright.yml@732a5e76b8177046ae89a3a216ca21ec21b28897 # v2.1.0
    with:
      hosting-provider: vercel
